// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExcludeAllIgnored
{
    internal sealed partial class Vsix
    {
        public const string Id = "ExcludeAllIgnored.5109ba88-4fcc-4c81-96e2-7c9237eebe2d";
        public const string Name = "ExcludeAllIgnored";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
