// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExcludeAllIgnored
{
    internal sealed partial class Vsix
    {
        public const string Id = "MSLaFaver.ExcludeAllIgnored";
        public const string Name = "Exclude all ignored files";
        public const string Description = @"Adds an option in the Tools menu to exclude all files from the solution's projects that are currently ignored according to the solution's Git repo. Created with GPT-5 for a personal project.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Michael LaFaver";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
