// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExcludeAllIgnored
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ExcludeAllIgnoredString = "a9ba6c4d-acc1-47a8-93d1-3eac702ef86c";
        public static Guid ExcludeAllIgnored = new Guid(ExcludeAllIgnoredString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MenuGroup = 0x0001;
        public const int ExcludeAllIgnoredFiles = 0x0100;
    }
}
