// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace ExcludeAllIgnored
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ExcludeAllIgnoredString = "a9ba6c4d-acc1-47a8-93d1-3eac702ef86c";
        public static Guid ExcludeAllIgnored = new Guid(ExcludeAllIgnoredString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int ExcludeAllIgnoredCommand = 0x0100;
    }
}